/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */
/** Analizador de expresiones aritmeticas sencillas. */
package analizadores;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MIENTRAS = 1;
  /** RegularExpression Id. */
  int FUNCION = 2;
  /** RegularExpression Id. */
  int RETORNO = 3;
  /** RegularExpression Id. */
  int BREAK = 4;
  /** RegularExpression Id. */
  int CONTINUE = 5;
  /** RegularExpression Id. */
  int SI = 6;
  /** RegularExpression Id. */
  int SINO = 7;
  /** RegularExpression Id. */
  int TRUE = 8;
  /** RegularExpression Id. */
  int FALSE = 9;
  /** RegularExpression Id. */
  int NULL = 10;
  /** RegularExpression Id. */
  int DEFA = 11;
  /** RegularExpression Id. */
  int PCOMA = 12;
  /** RegularExpression Id. */
  int COMA = 13;
  /** RegularExpression Id. */
  int PARENI = 14;
  /** RegularExpression Id. */
  int PAREND = 15;
  /** RegularExpression Id. */
  int CORI = 16;
  /** RegularExpression Id. */
  int CORD = 17;
  /** RegularExpression Id. */
  int LLAVEI = 18;
  /** RegularExpression Id. */
  int LLAVED = 19;
  /** RegularExpression Id. */
  int TERNARIO = 20;
  /** RegularExpression Id. */
  int DOSPUNTOS = 21;
  /** RegularExpression Id. */
  int MAS = 22;
  /** RegularExpression Id. */
  int MENOS = 23;
  /** RegularExpression Id. */
  int POR = 24;
  /** RegularExpression Id. */
  int MODULO = 25;
  /** RegularExpression Id. */
  int DIV = 26;
  /** RegularExpression Id. */
  int POTENCIA = 27;
  /** RegularExpression Id. */
  int IGUAL = 28;
  /** RegularExpression Id. */
  int MENORQUE = 29;
  /** RegularExpression Id. */
  int MAYORQUE = 30;
  /** RegularExpression Id. */
  int MENORIGUAL = 31;
  /** RegularExpression Id. */
  int MAYORIGUAL = 32;
  /** RegularExpression Id. */
  int IGUALACION = 33;
  /** RegularExpression Id. */
  int DIFERENCIACION = 34;
  /** RegularExpression Id. */
  int AND = 35;
  /** RegularExpression Id. */
  int OR = 36;
  /** RegularExpression Id. */
  int NOT = 37;
  /** RegularExpression Id. */
  int NUMERO = 38;
  /** RegularExpression Id. */
  int DECIMAL = 39;
  /** RegularExpression Id. */
  int ENTERO = 40;
  /** RegularExpression Id. */
  int CADENA = 41;
  /** RegularExpression Id. */
  int ID = 42;
  /** RegularExpression Id. */
  int STRING = 52;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRING_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"while\"",
    "\"Funcion\"",
    "\"Return\"",
    "\"Break\"",
    "\"continue\"",
    "\"if\"",
    "\"else\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"default\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"?\"",
    "\":\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"%%\"",
    "\"/\"",
    "\"^\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "<NUMERO>",
    "<DECIMAL>",
    "\"Numero\"",
    "\"Cadena\"",
    "<ID>",
    "\"\\\"\"",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 48>",
    "<token of kind 49>",
    "<token of kind 50>",
    "<token of kind 51>",
    "\"\\\"\"",
  };

}
