
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Twhile = 37;
  public static final int POR = 12;
  public static final int Treturn = 43;
  public static final int ENTERO = 45;
  public static final int DIFERENTE = 17;
  public static final int Tfuntion = 42;
  public static final int igual = 25;
  public static final int Tnull = 28;
  public static final int Tfor = 39;
  public static final int ternario = 26;
  public static final int Tswitch = 36;
  public static final int Tnot = 24;
  public static final int Tand = 23;
  public static final int MENORIGUAL = 21;
  public static final int CAD = 49;
  public static final int tdefault = 31;
  public static final int CORDER = 6;
  public static final int DIVIDIDO = 13;
  public static final int IGUALDAD = 16;
  public static final int Telse = 33;
  public static final int ttrue = 29;
  public static final int UMENOS = 47;
  public static final int LLAIZQ = 7;
  public static final int ID = 48;
  public static final int Tdo = 38;
  public static final int MAYORIGUAL = 20;
  public static final int DECIMAL = 46;
  public static final int EOF = 0;
  public static final int PARIZQ = 3;
  public static final int error = 1;
  public static final int COMA = 9;
  public static final int MODULO = 15;
  public static final int MENOS = 11;
  public static final int MENOR = 19;
  public static final int dospuntos = 27;
  public static final int MAYOR = 18;
  public static final int tfalse = 30;
  public static final int POTENCIA = 14;
  public static final int fantasmita = 44;
  public static final int Tcase = 35;
  public static final int Tin = 40;
  public static final int PTCOMA = 2;
  public static final int Tor = 22;
  public static final int Tbreak = 34;
  public static final int LLADER = 8;
  public static final int PARDER = 4;
  public static final int CORIZQ = 5;
  public static final int Tif = 32;
  public static final int Tcontinue = 41;
  public static final int MAS = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "CORIZQ",
  "CORDER",
  "LLAIZQ",
  "LLADER",
  "COMA",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "POTENCIA",
  "MODULO",
  "IGUALDAD",
  "DIFERENTE",
  "MAYOR",
  "MENOR",
  "MAYORIGUAL",
  "MENORIGUAL",
  "Tor",
  "Tand",
  "Tnot",
  "igual",
  "ternario",
  "dospuntos",
  "Tnull",
  "ttrue",
  "tfalse",
  "tdefault",
  "Tif",
  "Telse",
  "Tbreak",
  "Tcase",
  "Tswitch",
  "Twhile",
  "Tdo",
  "Tfor",
  "Tin",
  "Tcontinue",
  "Tfuntion",
  "Treturn",
  "fantasmita",
  "ENTERO",
  "DECIMAL",
  "UMENOS",
  "ID",
  "CAD"
  };
}

