
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Twhile = 45;
  public static final int plot = 24;
  public static final int POR = 13;
  public static final int Treturn = 52;
  public static final int array = 39;
  public static final int barplot = 26;
  public static final int ENTERO = 54;
  public static final int DIFERENTE = 18;
  public static final int Tfuntion = 51;
  public static final int igual = 31;
  public static final int Tprint = 49;
  public static final int Tnull = 34;
  public static final int Tfor = 47;
  public static final int ternario = 32;
  public static final int Tswitch = 44;
  public static final int Tnot = 30;
  public static final int Tand = 29;
  public static final int MENORIGUAL = 22;
  public static final int CAD = 58;
  public static final int tdefault = 37;
  public static final int CORDER = 6;
  public static final int DIVIDIDO = 14;
  public static final int IGUALDAD = 17;
  public static final int Telse = 41;
  public static final int list = 38;
  public static final int ttrue = 35;
  public static final int UMENOS = 56;
  public static final int LLAIZQ = 7;
  public static final int ID = 57;
  public static final int Tdo = 46;
  public static final int MAYORIGUAL = 21;
  public static final int DECIMAL = 55;
  public static final int EOF = 0;
  public static final int PARIZQ = 3;
  public static final int error = 1;
  public static final int COMA = 9;
  public static final int MODULO = 16;
  public static final int MENOS = 12;
  public static final int MENOR = 20;
  public static final int matrix = 27;
  public static final int dospuntos = 33;
  public static final int MAYOR = 19;
  public static final int tfalse = 36;
  public static final int POTENCIA = 15;
  public static final int fantasmita = 53;
  public static final int pie = 23;
  public static final int hist = 25;
  public static final int Tcase = 43;
  public static final int Tin = 48;
  public static final int PTCOMA = 2;
  public static final int Tor = 28;
  public static final int asigna = 10;
  public static final int Tbreak = 42;
  public static final int LLADER = 8;
  public static final int PARDER = 4;
  public static final int CORIZQ = 5;
  public static final int Tif = 40;
  public static final int Tcontinue = 50;
  public static final int MAS = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "CORIZQ",
  "CORDER",
  "LLAIZQ",
  "LLADER",
  "COMA",
  "asigna",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "POTENCIA",
  "MODULO",
  "IGUALDAD",
  "DIFERENTE",
  "MAYOR",
  "MENOR",
  "MAYORIGUAL",
  "MENORIGUAL",
  "pie",
  "plot",
  "hist",
  "barplot",
  "matrix",
  "Tor",
  "Tand",
  "Tnot",
  "igual",
  "ternario",
  "dospuntos",
  "Tnull",
  "ttrue",
  "tfalse",
  "tdefault",
  "list",
  "array",
  "Tif",
  "Telse",
  "Tbreak",
  "Tcase",
  "Tswitch",
  "Twhile",
  "Tdo",
  "Tfor",
  "Tin",
  "Tprint",
  "Tcontinue",
  "Tfuntion",
  "Treturn",
  "fantasmita",
  "ENTERO",
  "DECIMAL",
  "UMENOS",
  "ID",
  "CAD"
  };
}

